import { appTools, defineConfig } from '@modern-js/app-tools';
import { ModuleFederationPlugin } from '@module-federation/enhanced/rspack';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  server: {
    port: 3001,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
  tools: {
    rspack: (config, { appendPlugins }) => {
      // @ts-expect-error
      config.output.publicPath = 'auto';
      delete config.optimization?.splitChunks;
      appendPlugins([
        new ModuleFederationPlugin({
          name: 'checkout',
          runtime: false,
          filename: 'static/js/remoteEntry.js',
          remotes: {
            explore: 'explore@http://localhost:3000/static/js/remoteEntry.js',
          },
          exposes: {
            './MiniCart': './src/components/MiniCart',
            './AddToCart': './src/components/AddToCart',
            './CartPage': './src/routes/checkout/cart/page.js',
            './ThankYouPage': './src/routes/checkout/thanks/page.js',
          },
          shared: {
            react: { singleton: true },
            'react-dom': { singleton: true },
            '@modern-js/runtime/': { singleton: true },
          },
        }),
      ]);
    },
  },
});
