packages:
  - '**/**'
  - '!docs'
  - '!cypress'
  - '!angular14-react/*'
  - '!test'
  - '!multi-threaded-ssr/website2'
  - '!native-federation-react'
  - '!nextjs-ssr/*'
  - '!umd-federation/*'
  - '!cra-react-app-rewired/*'
  - '!runtime-plugins/remote-router'
