packages:
 - "advanced-api/automatic-vendor-sharing/*"
 - "advanced-api/automatic-vendor-sharing"
 - "advanced-api/dynamic-remotes/*"
 - "advanced-api/dynamic-remotes"
 - "advanced-api/dynamic-remotes-runtime-environment-variables/*"
 - "advanced-api/dynamic-remotes-runtime-environment-variables"
 - "advanced-api/dynamic-remotes-synchronous-imports/*"
 - "advanced-api/dynamic-remotes-synchronous-imports"
 - "angular-universal-ssr"
 - "angular11-microfrontends-ngrx"
 - "angular11-microfrontends-ngxs"
 - "angular12-microfrontends"
 - "umd-federation"
 - "umd-federation/*"
 - "angular14-react"
 - "angular14-react/*"
 - "angular15-vue3/*"
 - "apollo-client"
 - "apollo-client/*"
 - "basic-host-remote"
 - "basic-host-remote/*"
 - "bi-directional"
 - "bi-directional/*"
 - "cloud/azure-functions-node-v4"
 - "cloud/azure-functions-node-v4/*"
 - "complete-react-case"
 - "complete-react-case/*"
 - "comprehensive-demo-react16"
 - "comprehensive-demo-react16/*"
 - "comprehensive-demo-react18"
 - "comprehensive-demo-react18/*"
 - "cra"
 - "cra/*"
 - "remix/*"
 - "remix"
 - "cra-react-app-rewired"
 - "cra-react-app-rewired/*"
 - "css-isolation"
 - "css-isolation/*"
 - "cypress-e2e"
 - "react-storybook"
 - "react-storybook/*"
 - "delegate-modules"
 - "delegate-modules/*"
 - "different-react-versions"
 - "different-react-versions/*"
 - "different-react-versions-16-17"
 - "different-react-versions-16-17/*"
 - "different-react-versions-16-17-typescript"
 - "different-react-versions-16-17-typescript/*"
 - "different-react-versions-16-18"
 - "different-react-versions-16-18/*"
 - "different-react-versions-16-18-typescript"
 - "different-react-versions-16-18-typescript/*"
 - "different-react-versions-isolated"
 - "different-react-versions-isolated/*"
 - "different-react-versions-typescript"
 - "different-react-versions-typescript/*"
 - "dynamic-remotes-node"
 - "dynamic-remotes-node/*"
 - "dynamic-system-host"
 - "dynamic-system-host/*"
 - "federated-css"
 - "federated-css/consumers-nextjs/*"
 - "federated-css/consumers-react/*"
 - "federated-css/expose-remotes/*"
 - "federated-css-react-ssr"
 - "federated-css-react-ssr/*/*"
 - "federated-library-from-cdn"
 - "federated-library-from-cdn/*"
 - "federated-npm"
 - "federated-npm/*"
 - "self-healing"
 - "self-healing/*"
 - "frontend-discovery-service"
 - "frontend-discovery-service/*"
 - "genesis"
 - "genesis/*"
 - "i18next-nextjs-react"
 - "i18next-nextjs-react/*"
 - "loadable-react-16"
 - "loadable-react-16/*"
 - "loadable-react-18"
 - "loadable-react-18/*"
 - "modernjs"
 - "modernjs/*"
 - "modernjs-ssr"
 - "modernjs-ssr/*"
 - "typescript"
 - "typescript/*"
 - "typescript-monorepo/*"
 - "typescript-monorepo"
 - "typescript-project-references"
 - "typescript-project-references/*"
 - "typescript-react-fallback"
 - "typescript-react-fallback/*"
 - "typescript-react-monorepo"
 - "typescript-react-monorepo/*"
 - "typescript-react-monorepo-test"
 - "typescript-react-monorepo-test/*"
 - "!native-federation-react"
 - "native-federation-tests-typescript-plugins"
 - "native-federation-tests-typescript-plugins/*"
 - "nested"
 - "nested/*"
 - "nextjs-react"
 - "nextjs-react/*"
 - "nextjs-ssr"
 - "nextjs-ssr/*"
 - "nextjs-ssr-delegate-modules"
 - "nextjs-ssr-delegate-modules/*"
 - "nextjs-ssr-react-query"
 - "nextjs-v12"
 - "nextjs-v12/*"
 - "nextjs-v13"
 - "nextjs-v13/*"
 - "version-discrepancy"
 - "version-discrepancy/*"
 - "vite-react-microfrontends"
 - "vite-react-microfrontends/*"
 - "simple-node"
 - "simple-node/*"
 - "vite-react-simple"
 - "vite-react-simple/*"
 - "vite-svelte-microfrontends"
 - "vite-svelte-microfrontends/*"
 - "vite-vue-microfrontends"
 - "vite-vue-microfrontends/*"
 - "rust-wasm"
 - "rust-wasm/*"
 - "redux-reducer-injection"
 - "redux-reducer-injection/*"
 - "shared-routing"
 - "shared-routing/*"
 - "shared-routes2"
 - "shared-routes2/*"
 - "shared-context"
 - "shared-context/*"
 - "styled-components"
 - "styled-components/*"
 - "shared-store-cross-framework"
 - "shared-store-cross-framework/*"
 - "third-party-scripts"
 - "third-party-scripts/*"
 - "vue-cli"
 - "vue-cli/*"
 - "vue2-in-vue3"
 - "vue2-in-vue3/*"
 - "vue3-cli-demo/*"
 - "vue3-demo"
 - "vue3-demo/*"
 - "vue3-demo-federation-with-vite"
 - "vue3-demo-federation-with-vite/*"
 - "react-sharedworker"

