import { appTools, defineConfig } from '@modern-js/app-tools';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  server: {
    port: 3000,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
  tools: {
    rspack: (config, { rspack, appendPlugins }) => {
      // @ts-ignore
      config.output.publicPath = 'auto';
      appendPlugins([
        new rspack.container.ModuleFederationPlugin({
          name: 'explore',
          filename: 'static/js/remoteEntry.js',
          // remotes: {
          //   provider: 'provider@http://localhost:3002/static/js/remoteEntry.js',
          // },
          exposes: {
            './Header': './src/components/Header',
            './Footer': './src/components/Footer',
          },
          shared: {
            react: { singleton: true },
            'react-dom': { singleton: true },
          },
        }),
      ]);
    },
  },
});
