service: federeated_gateway
provider:
  name: aws
  runtime: nodejs12.x

package:
  include:
    - ./**/*
  exclude:
    - ./**/*

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ../.env

functions:
  federatedLambdaStreamingGateway:
    handler: server.server
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
