import { appTools, defineConfig } from '@modern-js/app-tools';
import { ModuleFederationPlugin } from '@module-federation/enhanced/rspack';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  server: {
    port: 3000,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
  output: {
    disableTsChecker: true,
  },
  tools: {
    rspack: (config, { rspack, appendPlugins }) => {
      // @ts-expect-error
      config.output.publicPath = 'auto';
      // @ts-expect-error
      config.output.uniqueName = 'explore';
      delete config.optimization?.splitChunks;

      appendPlugins([
        new rspack.container.ModuleFederationPlugin({
          name: 'explore',
          filename: 'static/js/remoteEntry.js',
          remotes: {
            decide: 'decide@http://localhost:3002/static/js/remoteEntry.js',
            checkout: 'checkout@http://localhost:3001/static/js/remoteEntry.js',
          },
          exposes: {
            './Header': './src/components/Header',
            './Footer': './src/components/Footer',
            './Recommendations': './src/components/Recommendations',
            './StorePicker': './src/components/StorePicker',
          },
          shared: {
            react: { singleton: true },
            'react-dom': { singleton: true },
            '@modern-js/': { singleton: true },
          },
        }),
      ]);
    },
  },
});
