import React from "react";
import { renderToString } from "react-dom/server";
import { Helmet } from "react-helmet";
import { ChunkExtractor } from "@loadable/server";
import path from "path";
import App from "../src/components/App";

// eslint-disable-next-line no-undef
const statsWebsite1 = __non_webpack_require__(
  "../buildClient/static/stats.json"
);
// eslint-disable-next-line no-undef
const statsWebsite2 = __non_webpack_require__(
  "../../website2/buildClient/static/stats.json"
);

function mergeStatsFiles(...files) {
  const mappedStats = files.map((stat) => {
    const { publicPath, assets, namedChunkGroups } = stat;

    const assetsWithPublicPath = assets.map((asset) => ({
      ...asset,
      name: `${publicPath}${asset.name}`,
    }));

    const namedChunkGroupsWithPublicPath = Object.fromEntries(
      Object.entries(namedChunkGroups).map((pair) => {
        const [name, data] = pair;

        data.assets = data.assets.map((asset) => `${publicPath}${asset}`);

        return [name, data];
      })
    );

    return {
      assets: assetsWithPublicPath,
      namedChunkGroups: namedChunkGroupsWithPublicPath,
    };
  });

  const initialStat = {
    publicPath: "/",
    outputPath: "",
    assets: [],
    namedChunkGroups: {},
  };

  return mappedStats.reduce(
    (acc, stat) => ({
      ...acc,
      assets: [...acc.assets, ...stat.assets],
      namedChunkGroups: {
        ...acc.namedChunkGroups,
        ...stat.namedChunkGroups,
      },
    }),
    initialStat
  );
}

const stats = mergeStatsFiles(statsWebsite1, statsWebsite2);

export default async (req, res, next) => {
  try {
    // This is the stats file generated by webpack loadable plugin
    // We create an extractor from the statsFile
    const extractor = new ChunkExtractor({ stats });
    // Wrap your application using "collectChunks"
    const jsx = extractor.collectChunks(createApp(App));

    // Render your application
    const html = renderToString(jsx);

    extractor.resolvePublicUrl = (filename) => filename;

    // You can now collect your script tags
    const scriptTags = extractor.getScriptTags(); // or extractor.getScriptElements();
    // You can also collect your "preload/prefetch" links
    const linkTags = extractor.getLinkTags(); // or extractor.getLinkElements();
    // And you can even collect your style tags (if you use "mini-css-extract-plugin")
    const styleTags = extractor.getStyleTags(); // or extractor.getStyleElements();
    // console.log('extractor',jsx)
    // console.log('scriptTags',scriptTags)

    // const appString = renderToString(app)
    const helmet = Helmet.renderStatic();

    // const chunkNames = flushChunkNames()
    // const { js, styles, cssHash } = flushChunks(clientStats, { chunkNames })
    // res.render('send', { csrfToken: req.csrfToken() })
    return res.send(`<!doctype html>
     <html ${helmet.htmlAttributes.toString()}>
        <head>
            ${helmet.title.toString()}
            ${helmet.meta.toString()}
            ${helmet.link.toString()}
          <script src="http://localhost:3002/static/container.js"></script>
            <link rel="shortcut icon" href="data:;base64,=">
            ${styleTags}
        </head>
       
        <body ${helmet.bodyAttributes.toString()}>
          <div id="root">${html}</div>
          ${scriptTags}
        </body>
      </html>`);
  } catch (err) {
    console.error(err);
  }
};

const createApp = (App) => <App />;
