import { appTools, defineConfig } from '@modern-js/app-tools';
import { ModuleFederationPlugin } from '@module-federation/enhanced/rspack';
// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  server: {
    port: 3002,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
  tools: {
    rspack: (config, { appendPlugins }) => {
      // @ts-expect-error
      config.output.publicPath = 'auto';
      // @ts-expect-error
      config.output.uniqueName = 'decide';
      delete config.optimization?.splitChunks;
      appendPlugins([
        new ModuleFederationPlugin({
          name: 'decide',
          runtime: false,
          filename: 'static/js/remoteEntry.js',
          remotes: {
            explore: 'explore@http://localhost:3000/static/js/remoteEntry.js',
            checkout: 'checkout@http://localhost:3001/static/js/remoteEntry.js',
          },
          exposes: {
            './ProductPage': './src/routes/product/[id]/page.js',
          },
          shared: {
            react: { singleton: true },
            'react-dom': { singleton: true },
            '@modern-js/runtime/router': { singleton: true },
          },
        }),
      ]);
    },
  },
});
