import * as React from 'react';
// @mf-typescript directory is autogenerated when you start the server
import RemoteButtonType from '../@mf-typescript/Button';

const RemoteButton = React.lazy(() => import('app2/Button')) as unknown as typeof RemoteButtonType;

const App = () => (
  <div>
    <h1>Typescript</h1>
    <h2>App 1</h2>
    <React.Suspense fallback="Loading Button">
      <RemoteButton size="large" />
      <br />
      <RemoteButton size="small" />
    </React.Suspense>
  </div>
);

export default App;
