import "./checkComrehensiveDemoReact18App1.cy"
import "./checkComrehensiveDemoReact18App2.cy"
import "./checkComrehensiveDemoReact18App3.cy"
import "./checkComrehensiveDemoReact18App4.cy"
import "./checkComrehensiveDemoReact18App5.cy"