import { appTools, defineConfig } from '@modern-js/app-tools';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  server: {
    port: 3001,
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
  ],
  tools: {
    rspack: (config, { rspack, appendPlugins }) => {
      // @ts-ignore
      config.output.publicPath = 'auto';
      appendPlugins([
        new rspack.container.ModuleFederationPlugin({
          name: 'checkout',
          filename: 'static/js/remoteEntry.js',
          remotes: {
            explore: 'explore@http://localhost:3000/static/js/remoteEntry.js',
          },
          exposes: {
            './MiniCart': './src/components/MiniCart',
          },
          shared: {
            react: { singleton: true },
            'react-dom': { singleton: true },
          },
        }),
      ]);
    },
  },
});
