name: on pull request closed
on:
  pull_request:
    types: [closed]

jobs:
  # Save nessesary env variables to use them in next jobs
  save-env:
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Save env variables
        run: |
          mkdir -p ./workflow
          echo "${{ github.event.pull_request.number }}" > ./workflow/prNum
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: env_for_cleanup
          path: workflow/